[versions]
java = "25"
vertx = "5.0.8"
slf4j = "2.0.17"
logback = "1.5.32"
guava = "33.5.0-jre"
guice = "7.0.0"
mug = "9.9.2"
jsr305 = "3.0.2"
errorprone = "2.47.0"
errorprone-plugin = "5.0.0"
checkstyle = "10.21.1"
spotbugs = "4.9.8" # Tool version
spotbugsPlugin = "6.4.8" # Plugin version
spotless = "8.2.1"
protobuf = "4.33.5"
protobufPlugin = "0.9.6"
junit = "6.0.3"
junit-platform = "6.0.3"
assertj = "3.27.7"
mockito = "5.21.0"
cucumber = "7.34.2"
jacoco = "0.8.14"
beanutils = "1.11.0"
log4j = "2.53.2"
commons-lang3 = "3.20.0"

[libraries]
# Core
vertx-core = { module = "io.vertx:vertx-core", version.ref = "vertx" }
vertx-codegen = { module = "io.vertx:vertx-codegen", version.ref = "vertx" }
vertx-junit5 = { module = "io.vertx:vertx-junit5", version.ref = "vertx" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

# Utilities
commons-beanutils = { module = "commons-beanutils:commons-beanutils", version.ref = "beanutils" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
guice = { module = "com.google.inject:guice", version.ref = "guice" }
mug = { module = "com.google.mug:mug", version.ref = "mug" }
mug-errorprone = { module = "com.google.mug:mug-errorprone", version.ref = "mug" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
errorprone-core = { module = "com.google.errorprone:error_prone_core", version.ref = "errorprone" }
errorprone-annotations = { module = "com.google.errorprone:error_prone_annotations", version.ref = "errorprone" }
spotbugs-annotations = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }
protobuf-java = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }

# Testing
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
assertj-guava = { module = "org.assertj:assertj-guava", version.ref = "assertj" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
cucumber-java = { module = "io.cucumber:cucumber-java", version.ref = "cucumber" }
cucumber-junit-platform-engine = { module = "io.cucumber:cucumber-junit-platform-engine", version.ref = "cucumber" }
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version = "1.4.1" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
spotbugs = { id = "com.github.spotbugs", version.ref = "spotbugsPlugin" }
errorprone = { id = "net.ltgt.errorprone", version.ref = "errorprone-plugin" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
